# DockerFiles/api/Dockerfile.api

FROM python:3.9-slim

# Upgrade pip
RUN pip install --upgrade pip

# Workdir
WORKDIR /app

# Copy requirements
COPY requirements.txt .
RUN pip install -r requirements.txt

# Copy the rest of the code
COPY . .

# Expose the port if you like (not strictly required)
EXPOSE 8000

# Run the Flask app
CMD ["python", "main.py"]
