# DockerFiles/airflow/Dockerfile.airflow

FROM apache/airflow:2.7.1

# Switch to root to install packages
USER root

# Copy requirements into the container
COPY ./DockerFiles/Airflow/requirements.txt /tmp/requirements.txt

# Install Python dependencies from requirements.txt
RUN su airflow -c "pip install --no-cache-dir -r /tmp/requirements.txt"
RUN apt-get update && apt-get install -y ffmpeg && rm -rf /var/lib/apt/lists/*

# Switch back to airflow user
USER airflow
